### ISSUE TITLE
Review requirements (add poetry)

### ISSUE THREAD

**Issue by ghomem** [Meaningful-Data/xbridge#2]
It would be useful to review the requirements so that xbridge is compatible with (at least) versions >= than the ones present on Ubuntu 24.04 LTS:

* python3-py7zr - 0.11.3
* python3-pandas - 2.1.4
* python3-lxml - 5.2.1

Currently xbrige is forcing newer versions for all these 3 libraries as dependencies but, unless it uses features that are very new, it might be that the these specific versions are not strictly necessary.

**Comment by javihern98** [comment]
For this change we require then to use poetry as dependencies manager

**Comment by javihern98** [comment]
Py7zr has been removed and Poetry has been used as internal project manager, instead of pipenv.
