### ISSUE TITLE
Identifier-scheme prefix for entity code is missing in parameters.csv

### ISSUE THREAD

**Issue by arjanpot** [Meaningful-Data/xbridge#4]
Hi, according to Filing rules 5.4, I expect a prefix to the entity code in the generated file **"parameters.csv"**.

The prefix would be **"rs:"** in case the identifier scheme is **https://eurofiling.info/eu/rs**.
The prefix would be **"lei:"** in case the identifier scheme is **http://standards.iso.org/iso/17442**.

Please check this document:
https://www.eba.europa.eu/sites/default/files/2024-07/e9d013bb-5f9a-4726-8e1b-d6b8b1d4289d/eba_filing_rules_v5.4_07_01.pdf 

The **"rs:"** prefix is also in the sample instances supplied by EBA. So I assume this is not implemented yet in xbridge.

Please let me know whether I am correct or not and if it can be fixed in xbridge.

Thanks!

**Comment by javihern98** [comment]
Hi @arjanpot, thanks for spotting this! @antonio-olleros please check it

**Comment by antonio-olleros** [comment]
Thanks a lot @arjanpot , we will implement this, we missed it.

I assume then that the right implementation is that we need to get the scheme attribute from the xbrli:identifier tag, like in this example:
<xbrli:identifier scheme="https://eurofiling.info/eu/rs">FR000.MEMSTAAGGCRDCREINS</xbrli:identifier>

And based on  that, add the prefix to the identifier. If you agree with that specification, we'll implement it.

**Comment by arjanpot** [comment]
Yes I think that's it. I did the same thing in my xbrl application. I am using xbridge to verify my output, as suggested by EBA/EIOPA.

Testing possibilities for XBRL-CSV are limited. Would be nice if you could double-check it. 
(or suggest other ways to test the xml to csv conversion)

Thanks a lot anyway!

**Comment by javihern98** [comment]
Fixed on #6
